### ISSUE TITLE
Not support SSR

### ISSUE THREAD

**Issue by Antoine-Demailly** [Degfy/vue-perfect-scrollbar#9]
It seems this package doesn't work with Server Side Rendering project:

```
ReferenceError: window is not defined
    at /path/to/project/node_modules/vue-perfect-scrollbar/dist/index.js:1:28820
    at /path/to/project/node_modules/vue-perfect-scrollbar/dist/index.js:1:28752
    at t.exports (/path/to/project/node_modules/vue-perfect-scrollbar/dist/index.js:1:29170)
    at Object.<anonymous> (/path/to/project/node_modules/vue-perfect-scrollbar/dist/index.js:1:29627)
    at e (/path/to/project/node_modules/vue-perfect-scrollbar/dist/index.js:1:177)
    at Object.module.exports.Object.defineProperty.value (/path/to/project/node_modules/vue-perfect-scrollbar/dist/index.js:1:9659)
    at e (/path/to/project/node_modules/vue-perfect-scrollbar/dist/index.js:1:177)
    at Object.module.exports.Object.defineProperty.value (/path/to/project/node_modules/vue-perfect-scrollbar/dist/index.js:1:9804)
    at e (/path/to/project/node_modules/vue-perfect-scrollbar/dist/index.js:1:177)
    at /path/to/project/node_modules/vue-perfect-scrollbar/dist/index.js:1:566
```

**Comment by Degfy** [comment]
yes. i plan support it in 1.x which will depend on  [perfect-scrollbar 1.x](https://github.com/utatti/perfect-scrollbar/releases/tag/1.3.0)

**Comment by Degfy** [comment]
@Antoine-Demailly i have no time to finish 1.x recently.however i submitted a commit for ssr in the repo，maybe you can test it. i will publish it if no bug.

**Comment by mavrick** [comment]
@Degfy - i tested with nuxtjs using the ``1.x`` branch and ssr - working fine. thank you

**Comment by byrnane** [comment]
So... If you fixed it, how can i get updated version?

**Comment by dillonburns** [comment]
@byrnane [here you go](https://github.com/Degfy/vue-perfect-scrollbar/archive/1.x.zip), I got it by going to the `<>code` tab, changing the branch to `1.x` and downloading it from there.

**Comment by TAnas0** [comment]
@Degfy With the rise of Nuxt.js and Server Side Rendering in general, could you please update the package on NPM?
Just for a cleaner install and since the version 1.0 is already ready, I suppose. If not, let us know what we can do to help.

Cheers

**Comment by TAnas0** [comment]
It is worth noting that you can install the version 1.0 of `vue-perfect-scrollbar` using:
```bash
npm install git+https://github.com/Degfy/vue-perfect-scrollbar.git#1.x
```

**Comment by LanFeusT23** [comment]
Is it completed though or still in dev? Hasn't been touched in 7 months.

**Comment by creativenoobie** [comment]
@Degfy Hey, Any updates on this? NPM package version is still 0.1.0.

**Comment by leafiy** [comment]
you need [nuxt plugin ](https://nuxtjs.org/guide/plugins#client-side-only)

**Comment by PaddeK** [comment]
I kind of solved it with a hack until this issue is resolved

```
require('require-extension-hooks')('js').push(({filename, content}) => {
    if (filename.endsWith('/node_modules/vue-perfect-scrollbar/dist/index.js')) {
        return ['!process.client && require("browser-env")()', content].join('\n');
    }
});
```
Put this in the nuxt app entry `/server/index.js`

**Comment by AlperMehmetOzdemir** [comment]
> It is worth noting that you can install the version 1.0 of `vue-perfect-scrollbar` using:
> 
> ```shell
> npm install git+https://github.com/Degfy/vue-perfect-scrollbar.git#1.x
> ```

When I run this npm can't seem to find the file. Do I have to manually download from github and add to node modules and update my package.json?

**Comment by woothu** [comment]
@Degfy can you tell when SSR will be available?

**Comment by handhikadj** [comment]
we need this so badly in nuxt

**Comment by woothu** [comment]
For everyone searching for this silution try out CScrollbar component from '@coreui/vue' library
